// File generated by FlutterFire CLI.
// This file should be replaced with your actual Firebase configuration
// Run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7Y2pM1yWePo_RcAYQ9kd_pdHuNN3D4k',
    appId: '1:286655438694:web:b388d41b3c6e4c196872a7',
    messagingSenderId: '286655438694',
    projectId: 'elektra-beb5b',
    authDomain: 'elektra-beb5b.firebaseapp.com',
    storageBucket: 'elektra-beb5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JzvX2DvFmWYr_Xi9RMFmUtPisUX7LyQ',
    appId: '1:286655438694:android:021693b3c9e693f76872a7',
    messagingSenderId: '286655438694',
    projectId: 'elektra-beb5b',
    storageBucket: 'elektra-beb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0GhtUyOXdYo9aBG83-3d6e4hLyZ__h6Q',
    appId: '1:286655438694:ios:e55bfc7e7097350f6872a7',
    messagingSenderId: '286655438694',
    projectId: 'elektra-beb5b',
    storageBucket: 'elektra-beb5b.firebasestorage.app',
    iosBundleId: 'com.example.trexy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0GhtUyOXdYo9aBG83-3d6e4hLyZ__h6Q',
    appId: '1:286655438694:ios:e55bfc7e7097350f6872a7',
    messagingSenderId: '286655438694',
    projectId: 'elektra-beb5b',
    storageBucket: 'elektra-beb5b.firebasestorage.app',
    iosBundleId: 'com.example.trexy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV7Y2pM1yWePo_RcAYQ9kd_pdHuNN3D4k',
    appId: '1:286655438694:web:0ee26867b30d06b36872a7',
    messagingSenderId: '286655438694',
    projectId: 'elektra-beb5b',
    authDomain: 'elektra-beb5b.firebaseapp.com',
    storageBucket: 'elektra-beb5b.firebasestorage.app',
  );

}